### ISSUE TITLE
About the mask annotation used 'box2seg.py'  and  '../_base_/datasets/uvo_finetune.py'

### ISSUE THREAD

**Issue by Cecilia-xue** [dulucas/UVO_Challenge#8]
Hi, @dulucas ,
In these two config files, many "mask annotations" are used, like in  this:

oid_train= dict(
        type='RepeatDataset',
        times=1,
        dataset=dict(
            type=dataset_type,
            data_root='data/oid/',
            img_dir = 'images/',
            ann_dir = 'masks/',
            split = ['train_clean_v2.txt', ],
            pipeline=train_pipeline
        )
)
and :
uvo_dense_val = dict(
        type='RepeatDataset',
        times=1,
        dataset=dict(
            type=dataset_type,
            data_root='data/uvo/',
            img_dir = 'images/dense_val/',
            ann_dir = 'masks/dense_val/',
            split = ['dense_val_list.txt', ],
            pipeline=train_pipeline
        )
)

And I tried the code like this[(https://github.com/alicranck/coco2voc)]()(url)  to generate the mask pngs, but there maybe something wrong with the generated masks, the training losses are  unusual.
Could you please provide the code or scripts that you used to generate the mask? or giving a link you are referred?

**Comment by dulucas** [comment]
Hi, the generation of mask is pretty simple, because I was in a rush and didn't have enough time to go through the code, I used the simplest yet most storage consuming way... The idea is to extract each instance mask from GT and save it as a single binary mask. For example, in the case of COCO dataset, if there are 9 instances in the image xxxx.jpg, then you can generate in total 9 binary masks with each of them containing a single instance(xxxx_001.png - xxxx_009.png for example).

**Comment by Cecilia-xue** [comment]
Thanks for kind reply！I will try it~
